/**
 * Paises para el selector del telefono.
 *
 * lada: clave del pais sin el "+". min/max: cuantos digitos lleva el numero
 * nacional, sin la lada ni el 0 de larga distancia. Los paises sin min/max
 * usan el rango general de la norma internacional (E.164): de 6 digitos
 * hasta completar 15 con la lada.
 *
 * Los nombres no se guardan aqui: los pone el navegador en el idioma de la
 * pagina (Intl.DisplayNames), asi "MX" sale "Mexico", "Mexico" o "Mê-hi-cô".
 *
 * El orden importa cuando varios paises comparten lada: el primero es el que
 * se elige al detectar "+1" (Estados Unidos) o "+7" (Rusia).
 */

/** Los que salen arriba de la lista, para no tener que buscarlos. */
export const PRINCIPALES = ['US', 'MX', 'CN', 'JP', 'VN']

export const PAISES = [
  // Principales
  { codigo: 'US', lada: '1', min: 10, max: 10 },
  { codigo: 'MX', lada: '52', min: 10, max: 10 },
  { codigo: 'CN', lada: '86', min: 10, max: 11 },
  { codigo: 'JP', lada: '81', min: 9, max: 10 },
  { codigo: 'VN', lada: '84', min: 9, max: 10 },

  // America del Norte y el Caribe con lada 1
  { codigo: 'CA', lada: '1', min: 10, max: 10 },
  { codigo: 'PR', lada: '1', min: 10, max: 10 },
  { codigo: 'DO', lada: '1', min: 10, max: 10 },
  { codigo: 'JM', lada: '1', min: 10, max: 10 },
  { codigo: 'TT', lada: '1', min: 10, max: 10 },
  { codigo: 'BS', lada: '1', min: 10, max: 10 },
  { codigo: 'BB', lada: '1', min: 10, max: 10 },

  // Centroamerica, Caribe y Sudamerica
  { codigo: 'GT', lada: '502', min: 8, max: 8 },
  { codigo: 'SV', lada: '503', min: 8, max: 8 },
  { codigo: 'HN', lada: '504', min: 8, max: 8 },
  { codigo: 'NI', lada: '505', min: 8, max: 8 },
  { codigo: 'CR', lada: '506', min: 8, max: 8 },
  { codigo: 'PA', lada: '507', min: 7, max: 8 },
  { codigo: 'BZ', lada: '501', min: 7, max: 7 },
  { codigo: 'CU', lada: '53', min: 8, max: 8 },
  { codigo: 'HT', lada: '509', min: 8, max: 8 },
  { codigo: 'CO', lada: '57', min: 10, max: 10 },
  { codigo: 'VE', lada: '58', min: 10, max: 10 },
  { codigo: 'EC', lada: '593', min: 8, max: 9 },
  { codigo: 'PE', lada: '51', min: 8, max: 9 },
  { codigo: 'BO', lada: '591', min: 8, max: 8 },
  { codigo: 'CL', lada: '56', min: 9, max: 9 },
  { codigo: 'AR', lada: '54', min: 10, max: 11 },
  { codigo: 'UY', lada: '598', min: 8, max: 8 },
  { codigo: 'PY', lada: '595', min: 9, max: 9 },
  { codigo: 'BR', lada: '55', min: 10, max: 11 },
  { codigo: 'GY', lada: '592', min: 7, max: 7 },
  { codigo: 'SR', lada: '597', min: 6, max: 7 },

  // Asia y Oceania
  { codigo: 'PH', lada: '63', min: 10, max: 10 },
  { codigo: 'KR', lada: '82', min: 9, max: 10 },
  { codigo: 'IN', lada: '91', min: 10, max: 10 },
  { codigo: 'TW', lada: '886', min: 8, max: 9 },
  { codigo: 'HK', lada: '852', min: 8, max: 8 },
  { codigo: 'MO', lada: '853', min: 8, max: 8 },
  { codigo: 'SG', lada: '65', min: 8, max: 8 },
  { codigo: 'TH', lada: '66', min: 8, max: 9 },
  { codigo: 'MY', lada: '60', min: 9, max: 10 },
  { codigo: 'ID', lada: '62', min: 9, max: 12 },
  { codigo: 'KH', lada: '855', min: 8, max: 9 },
  { codigo: 'LA', lada: '856', min: 8, max: 10 },
  { codigo: 'MM', lada: '95' },
  { codigo: 'BD', lada: '880' },
  { codigo: 'PK', lada: '92' },
  { codigo: 'LK', lada: '94' },
  { codigo: 'NP', lada: '977' },
  { codigo: 'AF', lada: '93' },
  { codigo: 'KP', lada: '850' },
  { codigo: 'MN', lada: '976' },
  { codigo: 'BT', lada: '975' },
  { codigo: 'MV', lada: '960' },
  { codigo: 'TL', lada: '670' },
  { codigo: 'AU', lada: '61', min: 9, max: 9 },
  { codigo: 'NZ', lada: '64', min: 8, max: 10 },
  { codigo: 'PG', lada: '675' },
  { codigo: 'FJ', lada: '679' },
  { codigo: 'WS', lada: '685' },
  { codigo: 'TO', lada: '676' },
  { codigo: 'SB', lada: '677' },
  { codigo: 'VU', lada: '678' },
  { codigo: 'KI', lada: '686' },
  { codigo: 'FM', lada: '691' },
  { codigo: 'MH', lada: '692' },

  // Medio Oriente y Asia Central
  { codigo: 'TR', lada: '90', min: 10, max: 10 },
  { codigo: 'IL', lada: '972', min: 8, max: 9 },
  { codigo: 'PS', lada: '970' },
  { codigo: 'SA', lada: '966', min: 9, max: 9 },
  { codigo: 'AE', lada: '971', min: 8, max: 9 },
  { codigo: 'QA', lada: '974' },
  { codigo: 'KW', lada: '965' },
  { codigo: 'BH', lada: '973' },
  { codigo: 'OM', lada: '968' },
  { codigo: 'YE', lada: '967' },
  { codigo: 'JO', lada: '962' },
  { codigo: 'LB', lada: '961' },
  { codigo: 'SY', lada: '963' },
  { codigo: 'IQ', lada: '964' },
  { codigo: 'IR', lada: '98' },
  { codigo: 'UZ', lada: '998' },
  { codigo: 'TJ', lada: '992' },
  { codigo: 'TM', lada: '993' },
  { codigo: 'KG', lada: '996' },
  { codigo: 'AZ', lada: '994' },
  { codigo: 'GE', lada: '995' },
  { codigo: 'AM', lada: '374' },

  // Europa
  { codigo: 'ES', lada: '34', min: 9, max: 9 },
  { codigo: 'PT', lada: '351', min: 9, max: 9 },
  { codigo: 'FR', lada: '33', min: 9, max: 9 },
  { codigo: 'IT', lada: '39', min: 6, max: 11 },
  { codigo: 'DE', lada: '49', min: 10, max: 11 },
  { codigo: 'GB', lada: '44', min: 10, max: 10 },
  { codigo: 'IE', lada: '353', min: 7, max: 9 },
  { codigo: 'NL', lada: '31', min: 9, max: 9 },
  { codigo: 'BE', lada: '32', min: 8, max: 9 },
  { codigo: 'CH', lada: '41', min: 9, max: 9 },
  { codigo: 'AT', lada: '43' },
  { codigo: 'LU', lada: '352' },
  { codigo: 'MC', lada: '377' },
  { codigo: 'AD', lada: '376' },
  { codigo: 'SM', lada: '378' },
  { codigo: 'MT', lada: '356' },
  { codigo: 'GI', lada: '350' },
  { codigo: 'DK', lada: '45', min: 8, max: 8 },
  { codigo: 'SE', lada: '46' },
  { codigo: 'NO', lada: '47', min: 8, max: 8 },
  { codigo: 'FI', lada: '358' },
  { codigo: 'IS', lada: '354' },
  { codigo: 'PL', lada: '48', min: 9, max: 9 },
  { codigo: 'CZ', lada: '420', min: 9, max: 9 },
  { codigo: 'SK', lada: '421', min: 9, max: 9 },
  { codigo: 'HU', lada: '36' },
  { codigo: 'RO', lada: '40', min: 9, max: 9 },
  { codigo: 'BG', lada: '359' },
  { codigo: 'GR', lada: '30', min: 10, max: 10 },
  { codigo: 'CY', lada: '357' },
  { codigo: 'HR', lada: '385' },
  { codigo: 'SI', lada: '386' },
  { codigo: 'BA', lada: '387' },
  { codigo: 'RS', lada: '381' },
  { codigo: 'ME', lada: '382' },
  { codigo: 'MK', lada: '389' },
  { codigo: 'AL', lada: '355' },
  { codigo: 'XK', lada: '383' },
  { codigo: 'LT', lada: '370' },
  { codigo: 'LV', lada: '371' },
  { codigo: 'EE', lada: '372' },
  { codigo: 'BY', lada: '375' },
  { codigo: 'UA', lada: '380', min: 9, max: 9 },
  { codigo: 'MD', lada: '373' },
  { codigo: 'RU', lada: '7', min: 10, max: 10 },
  { codigo: 'KZ', lada: '7', min: 10, max: 10 },
  { codigo: 'LI', lada: '423' },

  // Africa
  { codigo: 'EG', lada: '20', min: 10, max: 10 },
  { codigo: 'MA', lada: '212', min: 9, max: 9 },
  { codigo: 'DZ', lada: '213' },
  { codigo: 'TN', lada: '216' },
  { codigo: 'LY', lada: '218' },
  { codigo: 'SD', lada: '249' },
  { codigo: 'SS', lada: '211' },
  { codigo: 'ET', lada: '251' },
  { codigo: 'ER', lada: '291' },
  { codigo: 'DJ', lada: '253' },
  { codigo: 'SO', lada: '252' },
  { codigo: 'KE', lada: '254', min: 9, max: 9 },
  { codigo: 'UG', lada: '256' },
  { codigo: 'TZ', lada: '255' },
  { codigo: 'RW', lada: '250' },
  { codigo: 'BI', lada: '257' },
  { codigo: 'CD', lada: '243' },
  { codigo: 'CG', lada: '242' },
  { codigo: 'GA', lada: '241' },
  { codigo: 'GQ', lada: '240' },
  { codigo: 'CM', lada: '237' },
  { codigo: 'CF', lada: '236' },
  { codigo: 'TD', lada: '235' },
  { codigo: 'NG', lada: '234', min: 10, max: 10 },
  { codigo: 'NE', lada: '227' },
  { codigo: 'BJ', lada: '229' },
  { codigo: 'TG', lada: '228' },
  { codigo: 'GH', lada: '233' },
  { codigo: 'CI', lada: '225' },
  { codigo: 'BF', lada: '226' },
  { codigo: 'ML', lada: '223' },
  { codigo: 'LR', lada: '231' },
  { codigo: 'SL', lada: '232' },
  { codigo: 'GN', lada: '224' },
  { codigo: 'GW', lada: '245' },
  { codigo: 'SN', lada: '221' },
  { codigo: 'GM', lada: '220' },
  { codigo: 'MR', lada: '222' },
  { codigo: 'CV', lada: '238' },
  { codigo: 'ST', lada: '239' },
  { codigo: 'AO', lada: '244' },
  { codigo: 'ZM', lada: '260' },
  { codigo: 'ZW', lada: '263' },
  { codigo: 'MW', lada: '265' },
  { codigo: 'MZ', lada: '258' },
  { codigo: 'MG', lada: '261' },
  { codigo: 'MU', lada: '230' },
  { codigo: 'SC', lada: '248' },
  { codigo: 'KM', lada: '269' },
  { codigo: 'NA', lada: '264' },
  { codigo: 'BW', lada: '267' },
  { codigo: 'ZA', lada: '27', min: 9, max: 9 },
  { codigo: 'LS', lada: '266' },
  { codigo: 'SZ', lada: '268' },
]
